apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-app
  namespace: gitops-demo
spec:
  destination:
    namespace: gitops-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: child
    repoURL: https://github.com/gnunn1/app-of-app-test
    targetRevision: HEAD
syncPolicy:
  automated:
    prune: true
    selfHeal: true
