apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-catalog
  namespace: gitops-demo
spec:
  destination:
    namespace: gitops-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/gitops-examples/simple-app-example
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
